services:
  submission:
    public-key-content:  |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMrvuRMU9+bNlrnQ7sMsF97qzm/GB
      FZbjWToltYp4evQytGONcFZbMg3XqYp5DeiYRRAuuEUqgiYOQ11g/05p1g==
      -----END PUBLIC KEY-----
    verification:
      rate: 60000  # Every minute
    cleanup:
      tek:
        days: 10 # days
        rate: 60000  # Every minute
      ac:
        days: 10 # days
        rate: 60000  # Every minute
logging:
  level:
    app.coronawarn: DEBUG

management:
  metrics:
    export:
      cloudwatch:
        enabled: false
