services:
  submission:
    public-key-content:  |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMrvuRMU9+bNlrnQ7sMsF97qzm/GB
      FZbjWToltYp4evQytGONcFZbMg3XqYp5DeiYRRAuuEUqgiYOQ11g/05p1g==
      -----END PUBLIC KEY-----
    verification:
      rate: 60000  # Every minute
    cleanup:
      tek:
        days: 10 # days
        rate: 60000  # Every minute
      ac:
        days: 10 # days
        rate: 60000  # Every minute
    tek:
      dummy:
        rate: 60000
        min-range: 1
        max-range: 10
    monitoring:
      batch-size: 1
logging:
  level:
    app.coronawarn: DEBUG
